account/urls.py
from django.contrib import admin
from django.urls import path
from account import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path("change_password", views.Change_Password.as_view(), name='change_password')
]

socialite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls'), name='account_app'),
    path('userpage/', include('userpage.urls', namespace='userpage')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

userpage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import Search_User, EditProfile

app_name = 'userpage'

urlpatterns = [
    path('', views.userHome, name='userHome'),
    path('post', views.post, name='post'),
    path('like_dislike', views.likePost, name='like_dislike_post'),
    path("delete/<int:ID>", views.delPost, name='delpost'),
    path("<str:username>", views.userProfile, name='user_profile'),
    path("slug/comment", views.comment, name='comment'),
    path("user/follow/<str:username>", views.follow, name="follow"),
    path("search/", Search_User.as_view(), name="search_user"),
    path("<str:username>/edit", EditProfile.as_view(), name="editprofile"),

]

userpage/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = models.CharField(max_length=200)
    image = models.ImageField(upload_to = "Post")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + ' '+ str(self.date.date())


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    userImage = models.ImageField(upload_to = "Profiles", default = "default/default.png")
    bio = models.CharField(max_length=100, blank = True)
    connection = models.CharField(max_length = 100, blank=True)
    follower = models.IntegerField(default=0)
    following = models.IntegerField(default=0)


    def __str__(self):
        return str(self.user)

class Like(models.Model):
    user = models.ManyToManyField(User, related_name="linkingUser")
    post = models.OneToOneField(Post, on_delete=models.CASCADE)

    # for liking post
    @classmethod
    def like(cls, post, liking_user):
        obj, create  = cls.objects.get_or_create(post = post)
        obj.user.add(liking_user)

    # for disliking post
    @classmethod
    def dislike(cls, post, disliking_user):
        obj, create  = cls.objects.get_or_create(post = post)
        obj.user.remove(disliking_user)

    def __str__(self):
        return str(self.post)

class Following(models.Model):
    """ Following of the user """
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    followed = models.ManyToManyField(User, related_name="followed")
    follower = models.ManyToManyField(User, related_name="follower")

    @classmethod
    def follow(cls, user, another_account):
        obj = cls.objects.get(user = user)
        obj.followed.add(another_account)

    @classmethod
    def unfollow(cls, user, another_account):
        obj = cls.objects.get(user = user)
        obj.followed.remove(another_account)

    def __str__(self):
        return str(self.user)

class Share(Post, models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return str(self.user)

# P p ; { * " : _

userpage/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Post, Profile, Like, Following
from django.conf import settings
import json
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.views import View
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

def userHome(request):
    #fetching post from database
    user = Following.objects.get(user = request.user) #following_obj of user

    followed_users = user.followed.all()

    posts = Post.objects.filter(user__in = followed_users).order_by('-pk') | Post.objects.filter(user = request.user).order_by('-pk')
    liked_ = [i for i in posts if Like.objects.filter(post = i, user = request.user)]
    data = {
        'posts':posts,
        "liked_post":liked_
    }
    return render(request, "userpage/postfeed.html", data)

def post(request):
    if request.method=="POST":
        image_ = request.FILES['image']
        captions_ = request.POST.get('captions','')
        user_ = request.user
        post_obj = Post(user=user_, caption=captions_, image=image_)
        post_obj.save()
        messages.success(request, "We Showed Them!!!")
        return redirect('/')
    else:
        messages.error(request, "Something went Wrong :(")
        return redirect('/')


def delPost(request, ID):
    # every post have a unique identity
    post_ = Post.objects.filter(pk=ID)
    image_path = post_[0].image.url #image location in system
    post_.delete()
    messages.info(request, "Post Deleted")
    return redirect('/userpage')


def userProfile(request, username):
    user = User.objects.filter(username=username)
    if user:
        user = user[0]
        profile = Profile.objects.get(user=user)
        post = getPost(user)
        bio = profile.bio
        conn = profile.connection
        user_img = profile.userImage
        is_following = Following.objects.filter(user = request.user, followed = user)
        #create a Following objects
        following_obj = Following.objects.get(user = user)
        follower, following = following_obj.follower.count(), following_obj.followed.count()

        data = {
            'user_obj':user,
            'bio':bio,
            'conn':conn,
            'follower':follower,
            'following':following,
            'userImg':user_img,
            'posts':post,
            'connection':is_following
        }
    else: return HttpResponse("NO SUCH USER")

    return render(request, 'userpage/userProfile.html', data)


def getPost(user):
    post_obj = Post.objects.filter(user=user)
    imgList= [post_obj[i:i+3] for i in range(0, len(post_obj), 3)]
    return imgList


def likePost(request):
    post_id = request.GET.get("likeId", "")
    post = Post.objects.get(pk=post_id)
    user = request.user
    like = Like.objects.filter(post = post, user=user)
    liked = False

    if like:
        Like.dislike(post, user)
    else:
        liked = True
        Like.like(post, user)

    resp = {
        'liked':liked
    }
    response = json.dumps(resp)
    return HttpResponse(response, content_type = "application/json")

def comment(request):
    comment_ = request.GET.get('comment', '')
    print(comment_)
    return render(request, 'userpage/comments.html')

def follow(request, username):
    main_user = request.user
    to_follow = User.objects.get(username = username)

    #check if already following
    following = Following.objects.filter(user = main_user, followed = to_follow)
    is_following = True if following else False

    if is_following:
        Following.unfollow(main_user, to_follow)
        is_following = False
    else:
        Following.follow(main_user, to_follow)
        is_following = True

    resp = {
        "following" : is_following,
    }

    response = json.dumps(resp)
    return HttpResponse(response, content_type="application/json")

class Search_User(ListView):
    model = User
    template_name = "userpage/searchUser.html"
    paginate_by = 5 #page_obj
    def get_queryset(self):
        username = self.request.GET.get("username", None)
        queryset = User.objects.filter(username__icontains = username).order_by('-id')
        return queryset

class EditProfile(View):
    def post(self, request, *args, **kwargs):
        profile_obj = Profile.objects.get(user = request.user)
        bio = request.POST.get("Bio", "")
        img = request.FILES.get("image", "")
        if bio: profile_obj.bio = bio
        if img: profile_obj.userImage = img
        profile_obj.save()

        return HttpResponseRedirect(reverse("userpage:user_profile", args=(request.user.username,)))
# P _ { : ; p [ "

templates/userpage/comments.html
{% extends 'base.html' %}

{% block body %}
<div class="my-4 mx-4 container">
<form method="GET">
  <div class="form-group row">
    <label for="comment_text" class="col-sm-2 col-form-label">Comment</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" id="comment_text" name="comment">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Done</button>
</form>
</div>

<div class="container my-4 mx-4">
<div class="card">
  <div class="card-header">
    Username
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>Comment</p>
      <footer class="blockquote-footer">Duration<cite title="Source Title">Source Title</cite></footer>
    </blockquote>
  </div>
</div>
</div>
{% endblock body %}

templates/userpage/postfeed.html
{% extends 'base.html' %}
{% load static %}

{% block nav_btn1 %}
<button type="button" class="btn btn-outline-primary ml-4" data-toggle="modal" data-target="#PostModal">
    Post
</button>

{% endblock nav_btn1 %}

{% block css %}

    #post_img{
        width:460;
        heigt:360;
    }

    .post_div{
        width:535px;
    }

{% endblock css %}


{% block body %}

<div id="stories" class="storiesWrapper"></div>

{% for i in posts %}
<div class='container my-4 post_div' id="{{ i.id }}">
  <div class="card">
    <h5 class="card-header">
      <a href="{% url 'userpage:user_profile' i.user %}" style="color:black;">{{i.user}}</a>
      <small>{{i.date.date}}</small>
    </h5>
    <div class="card-body">
      <p class="card-text">{{i.caption}}</p>
      {% if i.image %}
        <img src="{{i.image.url}}" alt="Image" id='post_img'>
      {% endif %}
      <hr size='30px'>

      <button class="btn btn-light mr-3 like" id="{{ i.id }}">
        {% if i in liked_post %}
            <a href="{% url 'userpage:like_dislike_post' %}" style="color:red;" id="likebtn{{ i.id }}"> Liked </a>
        {% else %}
            <a href="{% url 'userpage:like_dislike_post' %}" style="color:red;" id="likebtn{{ i.id }}"> Like </a>
        {% endif %}
      </button>

      <a role = "button" class="btn btn-warning mx-2" href = "{% url 'userpage:comment' %}" >Comment</a>

      <button  class="btn btn-info mx-4" > Repost </button>
      {% if request.user == i.user %}
      <a class="btn btn-danger ml-4 delete" href="{% url 'userpage:delpost' i.id %}" id="{{ i.id }}">Delete</a>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}


{% endblock body %}

{% block modals %}

<!-- Modal -->
<div class="modal fade" id="PostModal" tabindex="-1" role="dialog" aria-labelledby="PostModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="PostModalLabel">Show Time</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/userpage/post" method="POST"  enctype="multipart/form-data">
          {% csrf_token %}
          <label for="image">Image : </label>
          <input type="file" name="image" id="image">
          <br><br><br>
          <label for="captions">Captions : </label>
          <br>
          <textarea name="captions" id="captions" cols="45" rows="10" placeholder="Oohlala..." class='ml-4'></textarea>
          <hr size='30'>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Let's Show</button>
        </form>
      </div>
    </div>
  </div>
</div>




{% endblock modals %}

{% block js %}

<script src="{% static 'userpage/js/delete.js' %}"></script>
<script src="{% static 'userpage/js/like.js' %}"></script>

{% endblock js %}

templates/userpage/searchUser.html
{% extends 'base.html' %}

{% block body %}

<div class="container my-4 mx-4">

    {% if not object_list %}
    <h1>No Search Results</h1>

    {% else %}
        {% for i in object_list %}
            <div class="card my-2">
                <div class="card-body">
                    <h2>{{i.username}}</h2>
                    <a type="button" name="button" class="btn btn-primary" role="button" href="{% url 'userpage:user_profile' i.username  %}" >View</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    {% if is_paginated %}
        <a href="?page=1" role="button" class="btn btn-outline-primary">First</a>

        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" role="button" class="btn btn-outline-primary">{{ page_obj.previous_page_number }}</a>
        {% endif %}

        {% if page_obj.number != 1 %}
        <a href="?page={{ page_obj.number }}" class="btn btn-primary">{{ page_obj.number }}</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" role="button" class="btn btn-outline-primary">{{ page_obj.next_page_number }}</a>
        {% endif %}

    {% endif %}

{% endblock body %}

templates/userpage/userProfile.html
{% extends 'base.html' %}


{% block css %}

.userImage
{
width:200px;
height:200px;
border-radius:50%;
}

.pst{
width:350px;
height:200px;
margin-bottom:30px;
}

.info
{
padding-top:2%;
padding-left:3%;
}

hr
{
border-top: 2px solid #000000;
}

#follow, #edit{
    color:blue;
}

#follow:hover, #edit:hover{
    color:white;
}
{% endblock css %}


{% block body %}

<div class="container my-4">
    <div class="media">
        <img src="{{userImg.url}}" class="align-self-start mr-3 userImage" alt="...">
        <div class="media-body info">
            <h4 class="mt-0">{{user_obj.username}}
                {% if request.user == user_obj %}
                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#EditModal">
                    Edit
                </button>
                {% elif connection %}
                <a type="button" class="btn btn-outline-primary" id="follow" role="button" href="{% url 'userpage:follow' user_obj.username %}">Unfollow</a>
                {% elif not connection %}
                <a type="button" class="btn btn-outline-primary" id="follow" role="button" href="{% url 'userpage:follow' user_obj.username %}">Follow</a>
                {% endif %}
            </h4>
            <p>Follower : {{follower}} Following : {{following}}</p>
            <p><b>{{bio}}</b></p>
        </div>
    </div>

    <hr>

    <div class='row'>
        {% for i in posts %}
        {% for j in i %}
        <div class='col-md-4'>
            <img src="{{j.image.url}}" alt="Image" class='pst'>
        </div>
        {% endfor %}
        {% endfor %}
    </div>
</div>

{% endblock body %}

{% block modals %}
<div class="modal fade" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="EditModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="EditModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form action="{{ request.user }}/edit" method="post"  enctype="multipart/form-data">
               {% csrf_token %}
            <div class="form-group">
              <label for="BioInput">Bio</label>
              <input type="text" class="form-control" id="BioInput" name="Bio">
              <br>
              <label for="image">Image : </label>
              <br>
              <input type="file" name="image" id="image">
            </div>
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Change</button>
      </div>
    </div>
  </div>
</div>
{% endblock modals %}

{% block js %}
<script type="text/javascript">
    $("#follow").click(function(e){
        e.preventDefault();
        var href = this.href;
        $.ajax({
            url : href,
            success : function(response){
                if(response["following"]){
                    $("#follow").html("Unfollow");
                }
                else{
                    $("#follow").html("Follow");
                }
            }
        })
    })
</script>
{% endblock js %}